// app/layout.tsx

import type { Metadata } from "next";
import { Inter, DM_Sans, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import LoadingManager from "@/components/LoadingManager";

const inter = Inter({ subsets: ["latin"] });
// const dmSans = DM_Sans({ subsets: ['latin'] });
const plusJakartaSans = Plus_Jakarta_Sans({ 
  subsets: ['latin'],
  preload: true,
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={plusJakartaSans.className}>
      <Navbar />
      <LoadingManager/>
      {children}
      <Footer />
      </body>
    </html>
  );
}

